spring:
  application:
    name: wanted-preonboarding-challenge-backend
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: dahye
    password: dahye

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect