spring:
  application:
    name: wanted-preonboarding-challenge-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/preonboarding
    username: root
    password: dahye

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database: mysql
    open-in-view: false

  data:
    redis:
      host: localhost # Redis 서버 호스트
      port: 6379      # Redis 서버 포트

  mail:
    host: smtp.gmail.com
    port: 587
    username: dahae80912@gmail.com
    password: wbuo zdju vwbb zqoi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  jwtSecret: 5TRwEzsnDlRL0mUTkKc2wHCy4auNF7AtLa9lE0HIo65v6QKHsJsDSNNeLilBEcnXxyiNCZN9zbEf6wtsUi1CbQ== #openssl rand -base64 64
